using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Singleton<T> : MonoBehaviour where T : Singleton<T>
{
    private static T instance;
    public static bool isClosed = false;
    public static T Instance
    {
        get {
            if (instance == null) {
                GameObject go = new GameObject(typeof(T).ToString());
                go.AddComponent<T>();
            }
            return instance;
        }
    }

    public virtual void Awake()
    {
        if (instance) {
            Destroy(gameObject);
        }
        else {
            instance = this as T;
            DontDestroyOnLoad(gameObject);
        }
    }

    public virtual void OnDestroy()
    {
        isClosed = true;
    }
}